version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1405_FPProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMSTest
  gitServerName: kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1405_fp.integrations:refdaf
  packages:
  - name: Kvv_1405_FPProject
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: JMSTest
    version: "1.0"
- serviceName: project.kvv_1405_fp.referencedata:ref1
  packages:
  - name: Kvv_1405_FPProject
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: JMSTest
    version: "1.0"
